<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyName>Firawynix-Kdenlive-Launcher</AssemblyName>
    <RootNamespace>Firawynix.Kdenlive.Launcher</RootNamespace>
    <ApplicationIcon>../../../data/icons/kdenlive.ico</ApplicationIcon>
    <Version>26.11.70-firaw.4</Version>
    <AssemblyVersion>26.11.70.4</AssemblyVersion>
    <FileVersion>26.11.70.4</FileVersion>
    <InformationalVersion>26.11.70-firaw.4</InformationalVersion>
  </PropertyGroup>
</Project>
